[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "bash start.sh"
healthcheckPath = "/api/cities/"
healthcheckTimeout = 360
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
