[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
preDeployCommand = "python manage.py migrate --noinput"
startCommand = "bash start.sh"
healthcheckPath = "/api/cities/"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
