# Generated by Django 5.0.6 on 2026-06-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_seed_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
