# Generated by Django 5.0.6 on 2026-06-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_extend_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='hero_image_attribution_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='city',
            name='hero_image_attribution_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='hero_image_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
