# Generated by Django 5.0.6 on 2026-06-03 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0008_seed_extra_cities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['-welcome_score', 'name'], 'verbose_name_plural': 'cities'},
        ),
    ]
