# Generated by Django 5.0.6 on 2026-06-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0010_replace_atlanta_with_sf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='google_place_id',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
