# Generated by Django 5.0.6 on 2026-06-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0013_seed_users_and_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='base_score',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Editorial seed score (counts as 10 user votes)', max_digits=3),
        ),
    ]
