# Generated by Django 5.0.6 on 2026-06-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0014_alter_city_base_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, unique=True)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('attribution_name', models.CharField(blank=True, max_length=200)),
                ('attribution_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
