# Generated by Django 5.0.6 on 2026-06-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0015_countryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='description_fr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='city',
            name='meta_description_fr',
            field=models.TextField(blank=True),
        ),
    ]
