[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python manage.py migrate --noinput && ./bin/start.sh"
healthcheckPath = "/api/0/organizations/"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
